### ISSUE TITLE
CV proposition

### ISSUE THREAD

**Issue by yannisgoo** [devpolo/community#2]
### Preflight checklist

- [X] I agree to follow this project's [Code of Conduct](https://github.com/devpolo/community/blob/main/CODE_OF_CONDUCT.md).

### Your proposal

Hello,  I'm a 4th year engineering student 👨‍🎓 at ECE Paris major connected objects, networks, and services.
 I would like to realize in the context of my studies an internship from April 11, 2022 for a period of 4-5 months abroad in a Hispanic or English environment 🌍. So I did this CV in a original way (developer ) , and i would like to know if you like it  if yes can you share it it could really help me. Thank you in advance.

Best regards , Y.G 
![desktop](https://user-images.githubusercontent.com/46002816/142826376-1a72cf82-1f20-4e5c-86c1-35fc6238f115.png)
![cv](https://user-images.githubusercontent.com/46002816/142826393-6f62f4e9-034a-4a56-ba27-d4000d073393.png)

### Source / Credit / Author

Yannis Gooré

### Link to your LinkedIn profile

www.linkedin.com/in/yannis-gooré-9439a7171

**Comment by yannisgoo** [comment]
I'm also interested in everything related to project management , (Project manager, Product manager, Product owner) etc.. It's not easy to find an internship moreover abroad , but i think you can help me .

Best regards Y.G ,

**Comment by devpolo** [comment]
Hi @yannisgoo 

I really appreciate your resume but it's currently not the purpose of this community / repo. I would love to help but I don't know how. Hope you will find what you are looking for.

**Comment by yannisgoo** [comment]
Do you speak french because i saw that you were at Paris ?
