### ISSUE TITLE
🎆 Meme proposition

### ISSUE THREAD

**Issue by skirscher** [devpolo/community#3]
### Preflight checklist

- [X] I agree to follow this project's [Code of Conduct](https://github.com/devpolo/community/blob/main/CODE_OF_CONDUCT.md).

### Your proposal

![Screenshot 2021-11-22 at 17-15-04 Working Your Spiceworks On-Prem Help Desk - Spiceworks](https://user-images.githubusercontent.com/15894157/142948833-1e2941fe-f5f1-400d-9902-65f953c10077.png)

When pop culture gets mixed into your tutorial examples ... I see what you did there Spiceworks.

### Source / Credit / Author

https://community.spiceworks.com/support/help-desk/docs/working-the-help-desk#tickets-anywhere

### Link to your LinkedIn profile

https://www.linkedin.com/in/stephen-kirscher/

**Comment by skirscher** [comment]
I submitted this not as a developer (though it is my background) but as an IT person who uses Spiceworks for their help desk ticketing... Thank you so much for the laughs, truly appreciate what JS does on LinkedIn.

**Comment by devpolo** [comment]
### Hi @skirscher 👋

> Thank you so much for the laughs, truly appreciate what JS does on LinkedIn.

Thank you very much for your support and your proposal as well. 

Regarding your meme. I'm not sure the community will get it. 

I want to share with you that a LinkedIn post must be, within 1 or 2 seconds, fast to read and easy to understand for thousands of people from different backgrounds.

Btw, thanks for sharing `Spiceworks`, I will have a look.

Feel free to create/share other memes 😀

Cheers

**Comment by skirscher** [comment]
I thought it was easy to get since it was John Snow but guess not everyone
is a Game of Thrones fan. Thanks for the feedback though. I look forward to
contributing more in the future.
